<?php

namespace App\Controllers;

use App\Models\UserModel;
use App\Models\AcademicYearModel;
use App\Models\SettingModel;
use App\Controllers\Tagihan;

class Pengaturan extends BaseController
{
    public function index()
    {
        $redirect = $this->redirectIfNotRole(['superadmin']);
        if ($redirect) return $redirect;

        $sekolah = $this->userData['sekolah'] ?? 'admin';
        $userModel = new UserModel();
        $taModel = new AcademicYearModel();

        $users = $sekolah === 'admin' ? $userModel->findAll() : $userModel->where('sekolah', $sekolah)->findAll();
        $academicYears = $taModel->orderBy('tahun_ajaran', 'DESC')->findAll();
        $activeTa = $taModel->where('aktif', 1)->first();

        $settingModel = new SettingModel();
        $data = [
            'title' => 'Pengaturan',
            'users' => $users,
            'sekolahUser' => $sekolah,
            'academicYears' => $academicYears,
            'activeTa' => $activeTa,
            'schoolName' => $settingModel->getSetting('school_name') ?? 'Al-Jawahir Attarbawi',
        ];

        return $this->render('pengaturan/index', $data);
    }

    public function setActiveTa()
    {
        $redirect = $this->redirectIfNotRole(['superadmin']);
        if ($redirect) return $redirect;

        if (($this->userData['sekolah'] ?? 'admin') !== 'admin') {
            return redirect()->back()->with('error', 'Hanya admin yang bisa mengubah tahun ajaran.');
        }

        $taModel = new AcademicYearModel();
        $newTaId = $this->request->getPost('tahun_ajaran_id');

        if (!$newTaId || !$taModel->find($newTaId)) {
            return redirect()->back()->with('error', 'Tahun ajaran tidak ditemukan.');
        }

        $taModel->db->table('tb_tahun_ajaran')->set('aktif', 0)->where('aktif', 1)->update();
        $taModel->update($newTaId, ['aktif' => 1]);

        // Carry over active students & teachers to the new academic year
        $db = \Config\Database::connect();
        $db->table('tb_siswa')->where('status', 'aktif')->set('tahun_ajaran_id', $newTaId)->update();
        $sekolah = $this->userData['sekolah'] ?? 'admin';
        if ($sekolah !== 'admin') {
            $db->table('tb_guru')->where('sekolah', $sekolah)->set('tahun_ajaran_id', $newTaId)->update();
        } else {
            $db->table('tb_guru')->set('tahun_ajaran_id', $newTaId)->update();
        }

        // Auto-buat tagihan daftar ulang untuk semua siswa aktif
        if (class_exists('\App\Controllers\Tagihan')) {
            $tagihan = new Tagihan();
            $tagihan->autoGenerateDaftarUlang();
        }

        return redirect()->to('/pengaturan')->with('success', 'Tahun ajaran aktif berhasil diubah.');
    }

    public function addTa()
    {
        $redirect = $this->redirectIfNotRole(['superadmin']);
        if ($redirect) return $redirect;

        if (($this->userData['sekolah'] ?? 'admin') !== 'admin') {
            return redirect()->back()->with('error', 'Hanya admin yang bisa menambah tahun ajaran.');
        }

        $rules = [
            'tahun_ajaran' => 'required|max_length[50]',
        ];

        if (!$this->validate($rules)) {
            return redirect()->back()->with('error', implode(' ', $this->validator->getErrors()));
        }

        $taModel = new AcademicYearModel();
        $taModel->insert([
            'tahun_ajaran' => $this->request->getPost('tahun_ajaran'),
            'aktif' => 0,
        ]);

        return redirect()->to('/pengaturan')->with('success', 'Tahun ajaran baru berhasil ditambahkan.');
    }

    public function store()
    {
        $redirect = $this->redirectIfNotRole(['superadmin']);
        if ($redirect) return $redirect;

        $sekolahUser = $this->userData['sekolah'] ?? 'admin';
        if ($sekolahUser !== 'admin') {
            return redirect()->back()->with('error', 'Hanya admin yang bisa menambah akun.');
        }

        $model = new UserModel();

        $rules = [
            'nama' => 'required|min_length[3]|max_length[100]',
            'email' => 'required|valid_email|is_unique[tb_users.email]',
            'password' => 'required|min_length[6]',
            'role' => 'required|in_list[admin,staff,kepala_sekolah]',
        ];

        if (!$this->validate($rules)) {
            return redirect()->back()->withInput()->with('error', implode(' ', $this->validator->getErrors()));
        }

        $data = [
            'nama' => $this->request->getPost('nama'),
            'email' => $this->request->getPost('email'),
            'password' => password_hash($this->request->getPost('password'), PASSWORD_DEFAULT),
            'role' => $this->request->getPost('role'),
            'sekolah' => $this->request->getPost('sekolah') ?: 'admin',
        ];

        $model->save($data);
        return redirect()->to('/pengaturan')->with('success', 'Akun berhasil ditambahkan.');
    }

    public function update()
    {
        $redirect = $this->redirectIfNotRole(['superadmin']);
        if ($redirect) return $redirect;

        $sekolahUser = $this->userData['sekolah'] ?? 'admin';
        if ($sekolahUser !== 'admin') {
            return redirect()->back()->with('error', 'Hanya admin yang bisa mengubah akun.');
        }

        $model = new UserModel();
        $id = $this->request->getPost('id');

        if (!$id || !$model->find($id)) {
            return redirect()->back()->with('error', 'Akun tidak ditemukan.');
        }

        $rules = [
            'nama' => 'required|min_length[3]|max_length[100]',
            'email' => "required|valid_email|is_unique[tb_users.email,id,{$id}]",
            'role' => 'required|in_list[admin,staff,kepala_sekolah]',
        ];

        if (!$this->validate($rules)) {
            return redirect()->back()->withInput()->with('error', implode(' ', $this->validator->getErrors()));
        }

        $data = [
            'nama' => $this->request->getPost('nama'),
            'email' => $this->request->getPost('email'),
            'role' => $this->request->getPost('role'),
            'sekolah' => $this->request->getPost('sekolah') ?: 'admin',
        ];

        $password = $this->request->getPost('password');
        if ($password) {
            $data['password'] = password_hash($password, PASSWORD_DEFAULT);
        }

        $model->update($id, $data);
        return redirect()->to('/pengaturan')->with('success', 'Akun berhasil diperbarui.');
    }

    public function delete()
    {
        $redirect = $this->redirectIfNotRole(['superadmin']);
        if ($redirect) return $redirect;

        $sekolahUser = $this->userData['sekolah'] ?? 'admin';
        if ($sekolahUser !== 'admin') {
            return redirect()->back()->with('error', 'Hanya admin yang bisa menghapus akun.');
        }

        $model = new UserModel();
        $id = $this->request->getPost('id');

        if (!$id) {
            return redirect()->back()->with('error', 'ID akun tidak valid.');
        }

        $user = $model->find($id);
        if (!$user) {
            return redirect()->back()->with('error', 'Akun tidak ditemukan.');
        }

        if ((int)$id === (int)$this->userData['id']) {
            return redirect()->back()->with('error', 'Tidak bisa menghapus akun sendiri.');
        }

        $model->delete($id);
        return redirect()->to('/pengaturan')->with('success', 'Akun berhasil dihapus.');
    }

    public function exportBackup()
    {
        $redirect = $this->redirectIfNotRole(['superadmin']);
        if ($redirect) return $redirect;

        if (($this->userData['sekolah'] ?? 'admin') !== 'admin') {
            return redirect()->back()->with('error', 'Hanya admin yang bisa melakukan backup.');
        }

        $db = \Config\Database::connect();
        $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

        $taModel = new \App\Models\AcademicYearModel();
        $activeTa = $taModel->where('aktif', 1)->first();
        $activeTaId = $activeTa ? $activeTa['id'] : 0;

        $tables = [
            'Kelas' => ['table' => 'tb_kelas', 'query' => 'SELECT * FROM tb_kelas ORDER BY id'],
            'Siswa' => ['table' => 'tb_siswa', 'query' => "SELECT s.nis, s.nama, s.jenis_kelamin, s.status, c.nama_kelas, s.sekolah, s.nominal_spp, s.nominal_awal_tahun, s.alamat, s.no_telp, s.aktif, s.nisn, s.tahun_ajaran_id, s.keterangan_pindah, s.id, s.created_at, s.updated_at FROM tb_siswa s LEFT JOIN tb_kelas c ON c.id = s.kelas_id WHERE s.tahun_ajaran_id = {$activeTaId} ORDER BY CASE s.sekolah WHEN 'ra' THEN 1 WHEN 'sd' THEN 2 WHEN 'smp' THEN 3 END, LENGTH(s.nis), s.nis"],
            'Guru' => ['table' => 'tb_guru', 'query' => 'SELECT * FROM tb_guru ORDER BY id'],
            'Tagihan' => ['table' => 'tb_tagihan_siswa', 'query' => 'SELECT * FROM tb_tagihan_siswa ORDER BY id'],
            'Pembayaran' => ['table' => 'tb_pembayaran', 'query' => 'SELECT * FROM tb_pembayaran ORDER BY id'],
            'Tabungan' => ['table' => 'tb_tabungan', 'query' => 'SELECT * FROM tb_tabungan ORDER BY id'],
            'Transaksi Tabungan' => ['table' => 'tb_transaksi_tabungan', 'query' => 'SELECT * FROM tb_transaksi_tabungan ORDER BY id'],
            'Pengguna' => ['table' => 'tb_users', 'query' => 'SELECT * FROM tb_users ORDER BY id'],
            'Tahun Ajaran' => ['table' => 'tb_tahun_ajaran', 'query' => 'SELECT * FROM tb_tahun_ajaran ORDER BY id'],
            'Pengaturan' => ['table' => 'tb_pengaturan', 'query' => 'SELECT * FROM tb_pengaturan ORDER BY id'],
        ];

        $sheetIndex = 0;
        foreach ($tables as $title => $cfg) {
            if ($sheetIndex === 0) {
                $sheet = $spreadsheet->getActiveSheet();
            } else {
                $sheet = $spreadsheet->createSheet();
            }
            $sheet->setTitle(substr($title, 0, 31));
            $sheetIndex++;

            $rows = $db->query($cfg['query'])->getResultArray();
            if (empty($rows)) {
                $sheet->setCellValue('A1', 'Tidak ada data');
                continue;
            }

            $columns = array_keys($rows[0]);

            foreach ($columns as $i => $col) {
                $cell = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($i + 1) . '1';
                $sheet->setCellValue($cell, $col);
            }
            $lastCol = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex(count($columns));
            $sheet->getStyle('A1:' . $lastCol . '1')->applyFromArray([
                'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF'], 'size' => 11],
                'fill' => ['fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID, 'startColor' => ['rgb' => '1E40AF']],
                'alignment' => ['horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER],
            ]);

            $rowNum = 2;
            foreach ($rows as $row) {
                foreach ($columns as $i => $col) {
                    $val = $row[$col] ?? '';
                    if ($col === 'password') $val = '(hidden)';
                    $cell = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($i + 1) . $rowNum;
                    $sheet->setCellValue($cell, $val);
                }
                $rowNum++;
            }

            foreach ($columns as $i => $col) {
                $colLetter = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($i + 1);
                $sheet->getColumnDimension($colLetter)->setAutoSize(true);
            }
        }

        $this->response->setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        $this->response->setHeader('Content-Disposition', 'attachment; filename="backup-lengkap-' . date('Y-m-d-Hi') . '.xlsx"');
        $this->response->setHeader('Cache-Control', 'max-age=0');

        $writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
        $writer->save('php://output');
    }

    public function deleteAllData()
    {
        $redirect = $this->redirectIfNotRole(['superadmin']);
        if ($redirect) return $redirect;

        if (($this->userData['sekolah'] ?? 'admin') !== 'admin') {
            return redirect()->back()->with('error', 'Hanya admin yang bisa menghapus data.');
        }

        $confirm = $this->request->getPost('confirm');
        if ($confirm !== 'HAPUS SEMUA') {
            return redirect()->back()->with('error', 'Ketik "HAPUS SEMUA" untuk konfirmasi.');
        }

        $db = \Config\Database::connect();
        $db->transBegin();

        try {
            $db->query('SET CONSTRAINTS ALL DISABLED');
            $db->table('tb_kas_yayasan')->truncate();
            $db->table('tb_pembayaran')->truncate();
            $db->table('tb_tagihan_siswa')->truncate();
            $db->table('tb_transaksi_tabungan')->truncate();
            $db->table('tb_transaksi_tht')->truncate();
            $db->table('tb_tabungan')->truncate();
            $db->table('tb_siswa')->truncate();
            $db->table('tb_guru')->truncate();
            $db->table('tb_kelas')->truncate();
            $db->query('SET CONSTRAINTS ALL ENABLED');

            $db->transCommit();
            return redirect()->to('/pengaturan')->with('success', 'Semua data berhasil dihapus. Data pengguna, tahun ajaran, dan pengaturan tetap aman.');
        } catch (\Exception $e) {
            $db->transRollback();
            return redirect()->back()->with('error', 'Gagal menghapus data: ' . $e->getMessage());
        }
    }

    public function importBackup()
    {
        $redirect = $this->redirectIfNotRole(['superadmin']);
        if ($redirect) return $redirect;

        if (($this->userData['sekolah'] ?? 'admin') !== 'admin') {
            return redirect()->back()->with('error', 'Hanya admin yang bisa restore backup.');
        }

        $file = $this->request->getFile('file_backup');
        if (!$file || !$file->isValid()) {
            return redirect()->back()->with('error', 'Pilih file backup terlebih dahulu.');
        }

        $ext = $file->getExtension();
        if (!in_array($ext, ['xlsx', 'xls'])) {
            return redirect()->back()->with('error', 'Format file harus .xlsx atau .xls.');
        }

        try {
            $reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader(ucfirst($ext));
            $reader->setReadDataOnly(true);
            $spreadsheet = $reader->load($file->getTempName());
        } catch (\Exception $e) {
            return redirect()->back()->with('error', 'Gagal membaca file: ' . $e->getMessage());
        }

        $db = \Config\Database::connect();
        $db->transBegin();
        try {
            $db->query('SET CONSTRAINTS ALL DISABLED');

            // Table order: classes → students → teachers → bills → bill_payments → savings_accounts → savings_transactions → users → academic_years → settings
            $sheetMap = [
                'Kelas'             => 'tb_kelas',
                'Siswa'             => 'tb_siswa',
                'Guru'              => 'tb_guru',
                'Tagihan'           => 'tb_tagihan_siswa',
                'Pembayaran'        => 'tb_pembayaran',
                'Tabungan'          => 'tb_tabungan',
                'Transaksi Tabungan' => 'tb_transaksi_tabungan',
                'Pengguna'          => 'tb_users',
                'Tahun Ajaran'      => 'tb_tahun_ajaran',
                'Pengaturan'        => 'tb_pengaturan',
            ];

            // Truncate existing data (reverse order)
            foreach (array_reverse($sheetMap) as $table) {
                $db->table($table)->truncate();
            }

            // Get actual column names for each table (to filter out extra export columns)
            $tableColumns = [];
            $colResult = $db->query('SELECT TABLE_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema = current_schema()');
            foreach ($colResult->getResultArray() as $colRow) {
                $tableColumns[$colRow['TABLE_NAME']][] = $colRow['COLUMN_NAME'];
            }

            $tingkatEnum = ['A','B','1','2','3','4','5','6','7','8','9'];

            foreach ($sheetMap as $sheetTitle => $table) {
                $sheet = $spreadsheet->getSheetByName($sheetTitle);
                if (!$sheet) continue;

                $rows = $sheet->toArray();
                if (count($rows) < 2) continue;

                $columns = $rows[0];
                if (empty(array_filter($columns))) continue;

                // Clean column names (remove BOM, trim)
                $columns = array_map(fn($c) => trim(preg_replace('/[\x00-\x1F\x80-\xFF]/', '', (string)$c)), $columns);

                // Only keep columns that exist in the table
                $validColumns = $tableColumns[$table] ?? [];
                $allowedIndices = [];
                $namaKelasIdx = null;
                foreach ($columns as $i => $col) {
                    if (!empty($col) && in_array($col, $validColumns, true)) {
                        $allowedIndices[] = $i;
                    }
                    if (strtolower(trim($col)) === 'nama_kelas') {
                        $namaKelasIdx = $i;
                    }
                }

                // For Siswa sheet: auto-create classes from nama_kelas before inserting
                if ($table === 'students' && $namaKelasIdx !== null) {
                    $sekolahIdx = null;
                    foreach ($columns as $i => $col) {
                        if (strtolower(trim($col)) === 'sekolah') {
                            $sekolahIdx = $i;
                            break;
                        }
                    }

                    // Collect existing classes
                    $existingClasses = [];
                    $existingResult = $db->query("SELECT nama_kelas, id FROM tb_kelas")->getResultArray();
                    foreach ($existingResult as $ec) {
                        $existingClasses[$ec['nama_kelas']] = $ec['id'];
                    }

                    // Auto-create missing classes — nama_kelas takes priority over kelas_id
                    foreach (array_slice($rows, 1) as $row) {
                        $nk = trim((string)($row[$namaKelasIdx] ?? ''));
                        if (empty($nk)) continue;
                        if (isset($existingClasses[$nk])) continue;

                        $sekolah = 'smp';
                        if ($sekolahIdx !== null) {
                            $sVal = trim((string)($row[$sekolahIdx] ?? ''));
                            if (in_array($sVal, ['ra', 'sd', 'smp'])) $sekolah = $sVal;
                        }

                        $tingkat = 'A';
                        if (preg_match('/^(\d+)-/', $nk, $m)) {
                            $tingkat = $m[1];
                        } elseif (preg_match('/^RA\s+(.+)/i', $nk, $m)) {
                            $tingkat = strtoupper(trim($m[1]));
                        } elseif (preg_match('/^([A-Z])\b/i', $nk, $m)) {
                            $tingkat = strtoupper($m[1]);
                        }
                        if (!in_array($tingkat, $tingkatEnum, true)) {
                            $tingkat = 'A';
                        }

                        $db->table('tb_kelas')->insert([
                            'nama_kelas' => $nk,
                            'tingkat'    => $tingkat,
                            'jurusan'    => null,
                            'sekolah'    => $sekolah,
                            'created_at' => date('Y-m-d H:i:s'),
                        ]);
                        $existingClasses[$nk] = $db->insertID();
                    }
                }

                $insertBatch = [];
                foreach (array_slice($rows, 1) as $row) {
                    $data = [];
                    $hasData = false;
                    foreach ($allowedIndices as $i) {
                        $col = $columns[$i];
                        $val = $row[$i] ?? '';
                        if ($val !== null && $val !== '') $hasData = true;
                        if ($col === 'password' && !empty($val)) {
                            if (!password_get_info($val)['algo']) {
                                $val = password_hash($val, PASSWORD_DEFAULT);
                            }
                        }
                        $data[$col] = $val === '' ? null : $val;
                    }

                    // For Siswa: nama_kelas always overrides kelas_id
                    if ($table === 'students' && $namaKelasIdx !== null) {
                        $nk = trim((string)($row[$namaKelasIdx] ?? ''));
                        if (!empty($nk) && isset($existingClasses[$nk])) {
                            $data['kelas_id'] = $existingClasses[$nk];
                        } elseif (empty($nk) && (!isset($data['kelas_id']) || empty($data['kelas_id']))) {
                            // Fallback: auto-create default class for this unit
                            $unit = $data['sekolah'] ?? 'smp';
                            $unitLabels = ['ra' => 'RA', 'sd' => 'SD', 'smp' => 'SMP'];
                            $defNk = $unitLabels[$unit] . ' A';
                            if (!isset($existingClasses[$defNk])) {
                                $db->table('tb_kelas')->insert([
                                    'nama_kelas' => $defNk,
                                    'tingkat'    => 'A',
                                    'jurusan'    => null,
                                    'sekolah'    => $unit,
                                    'created_at' => date('Y-m-d H:i:s'),
                                ]);
                                $existingClasses[$defNk] = $db->insertID();
                            }
                            $data['kelas_id'] = $existingClasses[$defNk];
                        }
                    }

                    if (!$hasData) continue;
                    $insertBatch[] = $data;
                }

                if (!empty($insertBatch)) {
                    $db->table($table)->insertBatch($insertBatch);
                }
            }

            // Sync bills with student data: update SPP & Daftar Ulang amounts
            $studentsAfter = $db->query("SELECT id, nominal_spp, nominal_awal_tahun FROM tb_siswa")->getResultArray();
            foreach ($studentsAfter as $sa) {
                if (!empty($sa['nominal_spp'])) {
                    $db->query("UPDATE tb_tagihan_siswa SET nominal = ? WHERE siswa_id = ? AND jenis_tagihan = 'SPP Bulanan' AND nominal != ?", [$sa['nominal_spp'], $sa['id'], $sa['nominal_spp']]);
                }
                if (!empty($sa['nominal_awal_tahun'])) {
                    $db->query("UPDATE tb_tagihan_siswa SET nominal = ? WHERE siswa_id = ? AND jenis_tagihan = 'Daftar Ulang' AND nominal != ?", [$sa['nominal_awal_tahun'], $sa['id'], $sa['nominal_awal_tahun']]);
                }
            }

            $db->query('SET CONSTRAINTS ALL ENABLED');
            $db->transCommit();
            return redirect()->to('/pengaturan')->with('success', 'Backup berhasil direstore. Semua data telah diimpor.');
        } catch (\Exception $e) {
            $db->query('SET CONSTRAINTS ALL ENABLED');
            $db->transRollback();
            return redirect()->back()->with('error', 'Gagal restore backup: ' . $e->getMessage());
        }
    }
}
