<?php

namespace App\Controllers;

use App\Models\BillModel;
use App\Models\BillPaymentModel;
use App\Models\StudentModel;
use App\Models\AcademicYearModel;
use App\Models\ClassModel;

class Tagihan extends BaseController
{
    public function index()
    {
        $redirect = $this->redirectIfNotRole(['superadmin', 'staff', 'kepala_sekolah']);
        if ($redirect) return $redirect;

        $sekolah = $this->userData['sekolah'] ?? 'admin';
        $billModel = new BillModel();
        $classModel = new ClassModel();
        $siswaModel = new StudentModel();
        $paymentModel = new BillPaymentModel();
        $taModel = new \App\Models\AcademicYearModel();
        $activeTa = $taModel->where('aktif', 1)->first();
        $taId = (int)($activeTa['id'] ?? 0);

        // Auto-generate SPP semua bulan & Daftar Ulang di tahun ajaran aktif jika belum ada (throttled to once per hour)
        $session = session();
        $lastAutoGen = $session->get('last_auto_gen_' . $sekolah);
        if (!$lastAutoGen || (time() - $lastAutoGen) > 3600) {
            $this->autoGenerateDaftarUlang($sekolah);
            $this->autoGenerateSpp($sekolah);
            $session->set('last_auto_gen_' . $sekolah, time());
        }

        $filters = [];
        $kelasId = $this->request->getGet('kelas');
        $status = $this->request->getGet('status');
        $jenis = $this->request->getGet('jenis');
        $search = $this->request->getGet('search');
        $bulan = $this->request->getGet('bulan') ?: date('n');
        if ($kelasId) $filters['kelas_id'] = $kelasId;
        if ($status) $filters['status'] = $status;
        if ($jenis) $filters['jenis'] = $jenis;
        if ($search) $filters['search'] = $search;
        $filters['bulan'] = $bulan;

        $bills = $billModel->getWithStudent($sekolah, $filters, 0, 0);
        $total = $billModel->getTotalCount($sekolah, $filters);
        $pager = \Config\Services::pager();
        $perPage = max(1, $total);
        $pager->makeLinks(1, $perPage, $total, 'default_full', 0, 'tagihan');

        // Summary dari total data terfilter (bukan cuma halaman ini)
        $summary = $billModel->getSummary($sekolah, $filters);
        $lunasCount = $summary['lunas_count'];
        $cicilCount = $summary['cicil_count'];
        $belumBayarCount = $summary['belum_bayar_count'];
        $totalTertagih = $summary['total_tertagih'];
        $totalTertunggak = $summary['total_tertunggak'];
        $siswaCount = $summary['siswa_count'];

        // Build payment lookup and cicilan tracking
        $allPayments = $paymentModel->findAll();
        $paymentLookup = [];
        $billCicilan = [];
        foreach ($allPayments as $p) {
            $paymentLookup[$p['tagihan_id']] = $p;
            if (!isset($billCicilan[$p['tagihan_id']])) {
                $billCicilan[$p['tagihan_id']] = ['total' => 0, 'count' => 0];
            }
            $billCicilan[$p['tagihan_id']]['total'] += (float)$p['nominal_dibayar'];
            $billCicilan[$p['tagihan_id']]['count']++;
        }

        // Build bill ID list for bill-modal lookups
        $billIds = array_column($bills, 'id');

        $siswaList = $siswaModel->getWithClass($sekolah);

        $data = [
            'title' => 'Tagihan & SPP',
            'bills' => $bills,
            'lunasCount' => $lunasCount,
            'cicilCount' => $cicilCount,
            'belumBayarCount' => $belumBayarCount,
            'totalTertagih' => $totalTertagih,
            'totalTertunggak' => $totalTertunggak,
            'classes' => $classModel->getFiltered($sekolah),
            'students' => $siswaList,
            'payments' => $paymentLookup,
            'billCicilan' => $billCicilan,
            'siswaCount' => $siswaCount,
            'kelas' => $kelasId ?? '',
            'status' => $status ?? '',
            'jenis' => $jenis ?? '',
            'search' => $search ?? '',
            'bulan' => $bulan ?? '',
            'pager' => $pager,
        ];

        return $this->render('tagihan/index', $data);
    }

    public function bayar()
    {
        $redirect = $this->redirectIfNotRole(['superadmin', 'staff', 'kepala_sekolah']);
        if ($redirect) return $redirect;

        $tagihanId = $this->request->getPost('tagihan_id');
        $metode = $this->request->getPost('metode') ?: 'tunai';
        $tglBayar = $this->request->getPost('tgl_bayar');
        $nominalDibayar = $this->request->getPost('nominal_dibayar');

        $billModel = new BillModel();
        $tagihan = $billModel->find($tagihanId);

        if (!$tagihan) {
            return redirect()->back()->with('error', 'Tagihan tidak ditemukan.');
        }

        $sekolah = $this->userData['sekolah'] ?? 'admin';
        if ($sekolah !== 'admin' && $tagihan['sekolah'] !== $sekolah) {
            return redirect()->back()->with('error', 'Anda tidak memiliki akses ke tagihan ini.');
        }

        if ($tagihan['status'] === 'lunas') {
            return redirect()->back()->with('error', 'Tagihan ini sudah lunas.');
        }

        $nominalDibayar = preg_replace('/[^0-9.,]/', '', $nominalDibayar);
        $nominalDibayar = (float) str_replace(',', '.', str_replace('.', '', $nominalDibayar));
        $sisaTagihan = (float)$tagihan['nominal'];

        // Check existing payments for cicilan tracking
        $paymentModel = new BillPaymentModel();
        $existingPayments = $paymentModel->where('tagihan_id', $tagihanId)->findAll();
        $totalDibayar = array_sum(array_column($existingPayments, 'nominal_dibayar'));
        $jumlahCicilan = count($existingPayments);

        // For Daftar Ulang, allow partial payment up to remaining balance
        if ($tagihan['jenis_tagihan'] === 'Daftar Ulang') {
            if ($nominalDibayar <= 0) {
                return redirect()->back()->with('error', 'Jumlah pembayaran harus lebih dari 0.');
            }
            $sisa = (float)$tagihan['nominal'] - $totalDibayar;
            if ($nominalDibayar > $sisa) {
                $nominalDibayar = $sisa;
            }
        } else {
            $nominalDibayar = (float)$tagihan['nominal'];
        }

        $db = \Config\Database::connect();
        $db->transBegin();

        try {
            $noKwitansi = 'KW-' . date('Y-m-d') . '-' . substr(md5(uniqid(mt_rand(), true)), 0, 8);

            $paymentModel->insert([
                'tagihan_id' => $tagihanId,
                'nominal_dibayar' => $nominalDibayar,
                'metode' => $metode,
                'no_kwitansi' => $noKwitansi,
                'user_id' => $this->userData['id'],
                'created_at' => $tglBayar ?: date('Y-m-d H:i:s'),
            ]);
            $paymentId = $db->insertID();

            // Auto-sync ke kas unit
            $sekolah = $tagihan['sekolah'] ?? '';
            $unit = null;
            if ($sekolah) {
                $db_ = \Config\Database::connect();
                $unit = $db_->query("SELECT * FROM tb_unit WHERE LOWER(nama) = LOWER(?) LIMIT 1", [$sekolah])->getRowArray();
                if (!$unit) {
                    $unit = $db_->query("SELECT * FROM tb_unit WHERE LOWER(nama) LIKE LOWER(?) LIMIT 1", ['%' . $sekolah . '%'])->getRowArray();
                }
            }
            if ($unit) {
                // Get nama siswa
                $siswaNama = '';
                $siswa = $db->table('tb_siswa')->where('id', $tagihan['siswa_id'])->get()->getRowArray();
                if ($siswa) $siswaNama = $siswa['nama'] ?? '';

                $kasUnitModel = new \App\Models\KasUnitModel();
                $kasUnitModel->insert([
                    'unit_id' => $unit['id'],
                    'tanggal' => $tglBayar ?: date('Y-m-d'),
                    'keterangan' => ($tagihan['jenis_tagihan'] ?? 'Tagihan') . ' ' . date('M Y', strtotime($tagihan['created_at'] ?? date('Y-m-d'))) . ' - ' . $siswaNama,
                    'kategori' => $tagihan['jenis_tagihan'] ?? 'Tagihan',
                    'jumlah' => $nominalDibayar,
                    'jenis' => 'pemasukan',
                    'metode' => $metode,
                    'status_tutup' => 'belum',
                    'user_id' => $this->userData['id'],
                    'referensi_id' => $paymentId,
                    'referensi_tipe' => 'pembayaran',
                ]);

            }

            $totalDibayarBaru = $totalDibayar + $nominalDibayar;
            $jumlahCicilanBaru = $jumlahCicilan + 1;

            if ($tagihan['jenis_tagihan'] === 'Daftar Ulang') {
                $isLunas = $totalDibayarBaru >= (float)$tagihan['nominal'] || $jumlahCicilanBaru >= 4;
                $billModel->update($tagihanId, ['status' => $isLunas ? 'lunas' : 'cicil']);
            } else {
                $billModel->update($tagihanId, ['status' => 'lunas']);
            }

            $db->transCommit();
            return redirect()->to('/tagihan/detail/' . $tagihanId)->with('success', "Pembayaran berhasil. Kwitansi: {$noKwitansi}");
        } catch (\Exception $e) {
            $db->transRollback();
            return redirect()->back()->with('error', $e->getMessage());
        }
    }

    public function detail($id)
    {
        $redirect = $this->redirectIfNotRole(['superadmin', 'staff', 'kepala_sekolah']);
        if ($redirect) return $redirect;

        $billModel = new BillModel();
        $paymentModel = new BillPaymentModel();

        $tagihan = $billModel->select('tb_tagihan_siswa.*, tb_siswa.nama, tb_siswa.nis, tb_kelas.nama_kelas, tb_kelas.tingkat, tb_kelas.jurusan, tb_tahun_ajaran.tahun_ajaran')
            ->join('tb_siswa', 'tb_siswa.id = tb_tagihan_siswa.siswa_id')
            ->join('tb_kelas', 'tb_kelas.id = tb_siswa.kelas_id')
            ->join('tb_tahun_ajaran', 'tb_tahun_ajaran.id = tb_tagihan_siswa.tahun_ajaran_id', 'left')
            ->find($id);

        if (!$tagihan) {
            return redirect()->to('/tagihan')->with('error', 'Tagihan tidak ditemukan.');
        }

        $sekolah = $this->userData['sekolah'] ?? 'admin';
        if ($sekolah !== 'admin' && $tagihan['sekolah'] !== $sekolah) {
            return redirect()->to('/tagihan')->with('error', 'Anda tidak memiliki akses ke tagihan ini.');
        }

        $payment = $paymentModel->select('tb_pembayaran.*, tb_users.nama as petugas_nama')
            ->join('tb_users', 'tb_users.id = tb_pembayaran.user_id', 'left')
            ->where('tagihan_id', $id)->first();

        $allPayments = $paymentModel->select('tb_pembayaran.*, tb_users.nama as petugas_nama')
            ->join('tb_users', 'tb_users.id = tb_pembayaran.user_id', 'left')
            ->where('tagihan_id', $id)
            ->orderBy('created_at', 'ASC')
            ->findAll();

        $data = [
            'title' => 'Detail Tagihan',
            'tagihan' => $tagihan,
            'payment' => $payment,
            'allPayments' => $allPayments,
        ];

        return $this->render('tagihan/detail', $data);
    }

    public function create()
    {
        $redirect = $this->redirectIfNotRole(['superadmin', 'staff', 'kepala_sekolah']);
        if ($redirect) return $redirect;

        $sekolah = $this->userData['sekolah'] ?? 'admin';

        $siswaId = $this->request->getPost('siswa_id');
        $jenisTagihan = $this->request->getPost('jenis_tagihan');

        $siswaModel = new StudentModel();
        $siswa = $siswaModel->find($siswaId);
        if (!$siswa) {
            return redirect()->back()->with('error', 'Siswa tidak ditemukan.');
        }

        if ($sekolah !== 'admin' && $siswa['sekolah'] !== $sekolah) {
            return redirect()->back()->with('error', 'Siswa tidak berada di sekolah Anda.');
        }

        // Use manual input if provided, otherwise auto-fill from student/class data
        $manualNominal = $this->request->getPost('nominal');
        if ($manualNominal && trim($manualNominal) !== '') {
            $nominal = (float) str_replace(',', '.', str_replace('.', '', $manualNominal));
        } elseif ($jenisTagihan === 'Daftar Ulang') {
            $nominal = (float)($siswa['nominal_awal_tahun'] ?? 0);
            if ($nominal <= 0 && !empty($siswa['kelas_id'])) {
                $classModel = new \App\Models\ClassModel();
                $class = $classModel->find($siswa['kelas_id']);
                $nominal = (float)($class['nominal_awal_tahun'] ?? 0);
            }
        } elseif ($jenisTagihan === 'SPP Bulanan') {
            $nominal = (float)($siswa['nominal_spp'] ?? 0);
            if ($nominal <= 0 && !empty($siswa['kelas_id'])) {
                $classModel = new \App\Models\ClassModel();
                $class = $classModel->find($siswa['kelas_id']);
                $nominal = (float)($class['nominal_spp'] ?? 0);
            }
        } else {
            $nominal = 0;
        }

        if ($nominal <= 0) {
            return redirect()->back()->with('error', 'Nominal tagihan tidak valid.');
        }

        $taModel = new AcademicYearModel();
        $ta = $taModel->where('aktif', 1)->first();

        $billModel = new BillModel();
        $data = [
            'siswa_id' => $siswaId,
            'jenis_tagihan' => $jenisTagihan,
            'sekolah' => $sekolah !== 'admin' ? $sekolah : $siswa['sekolah'],
            'nominal' => $nominal,
            'tahun_ajaran_id' => $ta['id'] ?? null,
            'status' => 'belum_bayar',
        ];

        if ($jenisTagihan === 'SPP Bulanan') {
            $data['created_at'] = date('Y-m-01 00:00:00');
        }

        $billModel->insert($data);

        return redirect()->back()->with('success', 'Tagihan baru berhasil dibuat.');
    }

    public function generateMonthlySpp()
    {
        $redirect = $this->redirectIfNotRole(['superadmin', 'staff', 'kepala_sekolah']);
        if ($redirect) return $redirect;

        $sekolah = $this->userData['sekolah'] ?? 'admin';
        $bulan = $this->request->getPost('bulan') ?: date('m');
        $tahun = $this->request->getPost('tahun') ?: date('Y');

        $taModel = new AcademicYearModel();
        $ta = $taModel->where('aktif', 1)->first();
        if (!$ta) {
            return redirect()->back()->with('error', 'Tidak ada tahun ajaran yang aktif.');
        }

        $siswaModel = new StudentModel();
        $query = $siswaModel->where('status', 'aktif')->where('tahun_ajaran_id', $ta['id']);
        if ($sekolah !== 'admin') {
            $query->where('sekolah', $sekolah);
        }
        $siswaList = $query->findAll();

        $billModel = new BillModel();
        $db = \Config\Database::connect();
        $created = 0;
        $skipped = 0;

        $firstDay = "{$tahun}-{$bulan}-01";
        $lastDay = date('Y-m-t', strtotime($firstDay));

        foreach ($siswaList as $siswa) {
            if (empty($siswa['nominal_spp']) || (float)$siswa['nominal_spp'] <= 0) {
                $skipped++;
                continue;
            }

            $existing = $db->query("
                SELECT id FROM tb_tagihan_siswa
                WHERE siswa_id = ? AND jenis_tagihan = 'SPP Bulanan'
                AND EXTRACT(MONTH FROM created_at)::int = ? AND EXTRACT(YEAR FROM created_at)::int = ?
                LIMIT 1
            ", [$siswa['id'], (int)$bulan, (int)$tahun])->getResultArray();

            if (!empty($existing)) {
                $skipped++;
                continue;
            }

            $db->table('tb_tagihan_siswa')->insert([
                'siswa_id' => $siswa['id'],
                'jenis_tagihan' => 'SPP Bulanan',
                'sekolah' => $siswa['sekolah'],
                'nominal' => (float)$siswa['nominal_spp'],
                'jatuh_tempo' => $lastDay,
                'tahun_ajaran_id' => $ta['id'],
                'status' => 'belum_bayar',
                'created_at' => $firstDay . ' 00:00:00',
            ]);
            $created++;
        }

        $monthName = \DateTime::createFromFormat('!m', $bulan)->format('F');
        return redirect()->back()->with('success', "SPP {$monthName} {$tahun}: {$created} tagihan dibuat, {$skipped} dilewati.");
    }

    public function autoGenerateSpp($sekolah = null)
    {
        $taModel = new AcademicYearModel();
        $ta = $taModel->where('aktif', 1)->first();
        if (!$ta) return;

        $bulanTA = $this->getBulanTA($ta['tahun_ajaran']);
        if (!$bulanTA) return;

        $siswaModel = new StudentModel();
        $classModel = new ClassModel();
        $billModel = new BillModel();
        $db = \Config\Database::connect();

        $siswaList = $siswaModel->where('status', 'aktif')->where('tahun_ajaran_id', $ta['id']);
        if ($sekolah && $sekolah !== 'admin') {
            $siswaList->where('sekolah', $sekolah);
        }
        $siswaList = $siswaList->findAll();

        foreach ($siswaList as $siswa) {
            $nominal = (float)($siswa['nominal_spp'] ?? 0);
            if ($nominal <= 0 && !empty($siswa['kelas_id'])) {
                $class = $classModel->find($siswa['kelas_id']);
                $nominal = (float)($class['nominal_spp'] ?? 0);
            }
            if ($nominal <= 0) continue;

            $tglMasuk = $siswa['tanggal_masuk'] ?? $siswa['created_at'] ?? date('Y-m-d');
            $thnBulanMulai = (int)date('Y', strtotime($tglMasuk)) * 100 + (int)date('n', strtotime($tglMasuk));

            // Check if student has Daftar Ulang bill for this TA
            $hasDu = $db->query(
                "SELECT id FROM tb_tagihan_siswa WHERE siswa_id = ? AND jenis_tagihan = 'Daftar Ulang' AND tahun_ajaran_id = ? LIMIT 1",
                [$siswa['id'], $ta['id']]
            )->getRowArray();

            $duBulan = $hasDu ? (int)date('n', strtotime($tglMasuk)) : 7;

            foreach ($bulanTA as $bulan) {
                // Skip SPP for the month covered by Daftar Ulang
                if ($hasDu && (int)$bulan['bulan'] === $duBulan) continue;
                // Skip months before student's entry date
                $thnBulan = (int)$bulan['tahun'] * 100 + (int)$bulan['bulan'];
                if ($thnBulan < $thnBulanMulai) continue;

                $firstDay = "{$bulan['tahun']}-{$bulan['bulan']}-01";
                $lastDay = date('Y-m-t', strtotime($firstDay));

                $existing = $db->query("
                    SELECT id FROM tb_tagihan_siswa
                    WHERE siswa_id = ? AND jenis_tagihan = 'SPP Bulanan'
                    AND EXTRACT(MONTH FROM created_at)::int = ? AND EXTRACT(YEAR FROM created_at)::int = ?
                    LIMIT 1
                ", [$siswa['id'], (int)$bulan['bulan'], (int)$bulan['tahun']])->getResultArray();

                if (!empty($existing)) continue;

                $billModel->insert([
                    'siswa_id' => $siswa['id'],
                    'jenis_tagihan' => 'SPP Bulanan',
                    'sekolah' => $siswa['sekolah'],
                    'nominal' => $nominal,
                    'jatuh_tempo' => $lastDay,
                    'tahun_ajaran_id' => $ta['id'],
                    'status' => 'belum_bayar',
                    'created_at' => $firstDay . ' 00:00:00',
                ]);
            }
        }
    }

    private function getBulanTA($tahunAjaran)
    {
        if (!preg_match('/^(\d{4})\/(\d{4})$/', $tahunAjaran, $m)) return null;
        $t1 = (int)$m[1];
        $t2 = (int)$m[2];
        $bulan = [];
        for ($b = 7; $b <= 12; $b++) $bulan[] = ['bulan' => str_pad($b, 2, '0', STR_PAD_LEFT), 'tahun' => $t1];
        for ($b = 1; $b <= 6; $b++) $bulan[] = ['bulan' => str_pad($b, 2, '0', STR_PAD_LEFT), 'tahun' => $t2];
        return $bulan;
    }

    public function autoGenerateDaftarUlang($sekolah = null)
    {
        $taModel = new AcademicYearModel();
        $ta = $taModel->where('aktif', 1)->first();
        if (!$ta) return;

        $siswaModel = new StudentModel();
        $classModel = new ClassModel();
        $billModel = new BillModel();

        $siswaList = $siswaModel->where('status', 'aktif')->where('tahun_ajaran_id', $ta['id']);
        if ($sekolah && $sekolah !== 'admin') {
            $siswaList->where('sekolah', $sekolah);
        }
        $siswaList = $siswaList->findAll();

        foreach ($siswaList as $siswa) {
            $nominalDu = (float)($siswa['nominal_awal_tahun'] ?? 0);
            if ($nominalDu <= 0 && !empty($siswa['kelas_id'])) {
                $class = $classModel->find($siswa['kelas_id']);
                $nominalDu = (float)($class['nominal_awal_tahun'] ?? 0);
            }
            if ($nominalDu <= 0) continue;

            $nominal = $nominalDu;

            $existing = $billModel->where('siswa_id', $siswa['id'])
                ->where('jenis_tagihan', 'Daftar Ulang')
                ->where('tahun_ajaran_id', $ta['id'])
                ->first();

            if ($existing) continue;

            $tglMasuk = $siswa['tanggal_masuk'] ?? null;
            if ($tglMasuk) {
                $duBulan = date('m', strtotime($tglMasuk));
                $duTahun = date('Y', strtotime($tglMasuk));
            } else {
                $t1 = (int) explode('/', $ta['tahun_ajaran'])[0];
                $duBulan = '07';
                $duTahun = $t1;
            }
            $duCreatedAt = "{$duTahun}-{$duBulan}-01 00:00:00";

            $billModel->insert([
                'siswa_id' => $siswa['id'],
                'jenis_tagihan' => 'Daftar Ulang',
                'sekolah' => $siswa['sekolah'],
                'nominal' => $nominal,
                'tahun_ajaran_id' => $ta['id'],
                'status' => 'belum_bayar',
                'created_at' => $duCreatedAt,
            ]);
        }
    }
}
